2025-02-24T23:03:44.476Z
Error: PostgreSQL connection error: error: password authentication failed for user "user"
    at getValidatedClient (C:\Users\sogoa\AppData\Roaming\npm\node_modules\@dbml\cli\node_modules\@dbml\connector\dist\connectors\postgresConnector.js:21:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchSchemaJson (C:\Users\sogoa\AppData\Roaming\npm\node_modules\@dbml\cli\node_modules\@dbml\connector\dist\connectors\postgresConnector.js:415:20)
    at async connectionHandler (C:\Users\sogoa\AppData\Roaming\npm\node_modules\@dbml\cli\lib\cli\connector.js:24:24)

2025-02-24T23:04:18.700Z
Error: PostgreSQL connection error: error: database "dbname" does not exist
    at getValidatedClient (C:\Users\sogoa\AppData\Roaming\npm\node_modules\@dbml\cli\node_modules\@dbml\connector\dist\connectors\postgresConnector.js:21:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchSchemaJson (C:\Users\sogoa\AppData\Roaming\npm\node_modules\@dbml\cli\node_modules\@dbml\connector\dist\connectors\postgresConnector.js:415:20)
    at async connectionHandler (C:\Users\sogoa\AppData\Roaming\npm\node_modules\@dbml\cli\lib\cli\connector.js:24:24)

